In [49]:
import pandas as pd
import matplotlib.pyplot as plt 
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error
from sklearn.metrics import root_mean_squared_error,mean_absolute_error
from sklearn.metrics import r2_score

In [51]:
df=pd.read_csv("temperature_linear_regression_data.csv")

In [52]:
print(df.head())

   Temperature_C  IceCream_Sales
0           36.8           313.0
1           29.7           247.0
2           30.6           267.0
3           39.1           349.0
4           30.7           251.0

In [53]:
df.shape

(500, 2)

In [54]:
print(df.isnull(). sum())

Temperature_C     15
IceCream_Sales    15
dtype: int64

In [55]:
df=df.dropna()

In [56]:
print(df.isnull(). sum())

Temperature_C     0
IceCream_Sales    0
dtype: int64

In [57]:
print(df.duplicated().sum())

8

In [58]:
df=df.drop_duplicates()

In [59]:
print(df.duplicated().sum())

0

In [60]:
df.dtypes

Temperature_C     float64
IceCream_Sales    float64
dtype: object

In [61]:
df.describe()

       Temperature_C  IceCream_Sales
count     462.000000      462.000000
mean       29.911255      251.196970
std         8.918338       98.230009
min        15.200000       80.000000
25%        22.225000      172.000000
50%        30.350000      251.000000
75%        37.600000      326.500000
max        44.800000      665.000000

In [62]:
df[df["IceCream_Sales"]< 0]

Empty DataFrame
Columns: [Temperature_C, IceCream_Sales]
Index: []

In [63]:
Q1 = df["Temperature_C"].quantile(0.25)
Q3 = df["Temperature_C"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[
    (df["Temperature_C"] < lower) |
    (df["Temperature_C"] > upper)
]

print(outliers)

Empty DataFrame
Columns: [Temperature_C, IceCream_Sales]
Index: []

In [64]:
Q1 = df["IceCream_Sales"].quantile(0.25)
Q3 = df["IceCream_Sales"].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower Bound:", lower)
print("Upper Bound:", upper)

outliers = df[
    (df["IceCream_Sales"] < lower) |
    (df["IceCream_Sales"] > upper)
]

print("Outliers:")
print(outliers)
print("Number of outliers:", len(outliers))

Lower Bound: -59.75
Upper Bound: 558.25
Outliers:
     Temperature_C  IceCream_Sales
84            40.1           649.0
145           37.7           629.0
360           43.9           665.0
417           35.9           636.0
Number of outliers: 4

In [65]:
df_clean = df[
    (df["IceCream_Sales"] >= lower) &
    (df["IceCream_Sales"] <= upper)
].copy()

print("Before:", len(df))
print("After:", len(df_clean))

Before: 462
After: 458

In [66]:
X= df[["Temperature_C"]]
y=df["IceCream_Sales"]

In [67]:
X_train,X_test,y_train,y_test=train_test_split(

X,
y,
test_size=0.2,
random_state=12
)

In [68]:
X_train

     Temperature_C
312           38.1
48            26.7
286           18.2
151           23.1
429           38.6
..             ...
258           27.6
272           26.6
424           29.7
167           24.9
359           34.0

[369 rows x 1 columns]

In [69]:
X_test

     Temperature_C
483           25.1
308           34.1
6             28.2
248           41.6
269           23.6
..             ...
56            16.4
481           38.9
357           26.7
73            16.4
324           34.6

[93 rows x 1 columns]

In [70]:
y_train

312    323.0
48     221.0
286    111.0
151    167.0
429    319.0
       ...
258    225.0
272    217.0
424    238.0
167    191.0
359    107.0
Name: IceCream_Sales, Length: 369, dtype: float64

In [71]:
y_test

483    224.0
308    298.0
6      237.0
248    369.0
269    176.0
       ...
56     119.0
481    339.0
357    222.0
73     103.0
324    289.0
Name: IceCream_Sales, Length: 93, dtype: float64

In [72]:
model=LinearRegression()

In [73]:
model.fit(X_train,y_train)

LinearRegression()

In [74]:
model.intercept_

np.float64(-49.00470017156081)

In [75]:
model.coef_

array([10.04524858])

In [76]:
y= model.predict(X_test)

y

array([203.13103922, 293.53827645, 234.27130982, 368.87764081,
       188.06316635, 400.01791142, 282.48850301, 265.41158043,
       179.02244263, 125.78262514, 204.13556408, 166.96814433,
       211.16723809, 359.83691709, 259.38443128, 346.77809393,
       394.99528712, 128.79619972, 187.05864149, 154.91384603,
       339.74641993, 189.06769121, 249.3391827 , 313.62877362,
       393.99076227, 143.86407259, 328.69664649, 160.94099518,
       347.78261879, 201.1219895 , 251.34823241, 363.85501652,
       112.72380199, 107.7011777 , 129.80072458, 250.34370755,
       374.90478996, 296.55185103, 268.425155  , 168.97719404,
       126.78715   , 333.71927078, 175.00434319, 118.75095114,
       316.64234819, 153.90932117, 254.36180699, 265.41158043,
       341.75546964, 229.24868553, 123.77357543, 369.88216567,
       365.86406624, 329.70117135, 198.10841493, 323.6740222 ,
       357.82786737, 278.47040358, 186.05411663, 320.66044762,
       244.3165584 , 103.68307827, 148.88669688, 209.15818837,
       128.79619972, 323.6740222 , 371.89121539, 288.51565216,
       399.01338656, 257.37538156, 212.17176294, 193.08579064,
       395.99981198, 105.69212798, 269.42967986, 110.71475227,
       253.35728213, 250.34370755, 345.77356908, 197.10389007,
       128.79619972, 218.19891209, 160.94099518, 175.00434319,
       379.92741425, 106.69665284, 286.50660245, 177.01339291,
       115.73737656, 341.75546964, 219.20343695, 115.73737656,
       298.56090074])

In [77]:
result=pd.DataFrame({

  "actual":y_test.values,
  "predict":y

})

result

    actual     predict
0    224.0  203.131039
1    298.0  293.538276
2    237.0  234.271310
3    369.0  368.877641
4    176.0  188.063166
..     ...         ...
88   119.0  115.737377
89   339.0  341.755470
90   222.0  219.203437
91   103.0  115.737377
92   289.0  298.560901

[93 rows x 2 columns]

In [78]:
mse=mean_squared_error(y_test,y)

mse

178.01576422299934

In [79]:
rmse=root_mean_squared_error(y_test,y)

mse

178.01576422299934

In [80]:
mae=mean_absolute_error(y_test,y)

mae

10.5849136884468

In [81]:
r2=r2_score(y_test,y)

r2

0.9799747315457389

In [112]:
temp=float(input("entet u r tempreture"))

In [113]:

newdata=pd.DataFrame({
    "Temperature_C":[temp]
})
mynewdata=model.predict(newdata)
print(mynewdata[0])

16.430411646425668